### ISSUE TITLE
import dirt error

### ISSUE THREAD

**Issue by willfu** [pmh47/dirt#22] opened 2019-05-12 23:35 UTC
>>> import dirt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/will/dirt/dirt/__init__.py", line 2, in <module>
    from rasterise_ops import rasterise, rasterise_batch
  File "/home/will/dirt/dirt/rasterise_ops.py", line 7, in <module>
    _rasterise_module = tf.load_op_library(_lib_path + '/librasterise.so')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/will/dirt/dirt/librasterise.so: undefined symbol: _ZN10tensorflow7strings8internal9CatPiecesB5cxx11ESt16initializer_listIN4absl11string_viewEE
>>> 

after pip install to import dirt, the errors as above
env:python 2.7, tensorflow is 1.13.1 gpu version, thanks.

**Comment by pmh47** [comment] 2019-05-13 11:12
This is a duplicate of #10, see the last two comments on that issue for the cause and solution.

**Closed by pmh47** 2019-05-13 11:12 UTC
