### ISSUE TITLE
none of 1 egl devices matches the active cuda device

### ISSUE THREAD

**Issue by au001** [pmh47/dirt#59] opened 2020-03-08 02:16 UTC
I am getting the exact same error message as @Qingcsai in #54 -

```
I have no name!@2bcd5592e454:~/dirt$ python tests/square_test.py
WARNING:tensorflow:From tests/square_test.py:41: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-03-07 23:08:54.864182: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-03-07 23:08:57.912261: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: Tesla V100-PCIE-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:21:00.0
2020-03-07 23:08:57.912894: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-03-07 23:08:57.915643: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-03-07 23:08:57.918103: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-03-07 23:08:57.918696: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-03-07 23:08:57.921856: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-03-07 23:08:57.924259: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-03-07 23:08:57.930714: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-07 23:08:57.938051: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-03-07 23:08:57.939114: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-07 23:08:57.959327: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1995940000 Hz
2020-03-07 23:08:57.964453: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55605835f450 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-07 23:08:57.964538: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-03-07 23:08:58.078474: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x556058bc90d0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-03-07 23:08:58.078525: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla V100-PCIE-32GB, Compute Capability 7.0
2020-03-07 23:08:58.080621: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: Tesla V100-PCIE-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:21:00.0
2020-03-07 23:08:58.080679: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-03-07 23:08:58.080727: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-03-07 23:08:58.080768: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-03-07 23:08:58.080801: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-03-07 23:08:58.080848: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-03-07 23:08:58.080869: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-03-07 23:08:58.080924: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-07 23:08:58.084960: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-03-07 23:08:58.085039: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-03-07 23:08:58.087362: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-07 23:08:58.087391: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2020-03-07 23:08:58.087447: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2020-03-07 23:08:58.091489: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30555 MB memory) -> physical GPU (device: 0, name: Tesla V100-PCIE-32GB, pci bus id: 0000:21:00.0, compute capability: 7.0)
2020-03-07 23:08:59.132281: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-03-07 23:08:59.136092: F /tmp/pip-req-build-rzlvw14z/csrc/gl_common.h:65] none of 1 egl devices matches the active cuda device
Aborted (core dumped)
```

We have used the modified Dockerfile as-is in [this gist](https://gist.github.com/pmh47/597229ce113fa51e9197647464fdfeed) that @pmh47 has provided in #34.

We have tried several different combinations of CUDA, CUDNN, Ubuntu, and TensorFlow versions for creating DIRT Docker images and this is the combination that has brought us thus far:
export CUDA_BASE_VERSION=10.0 
export CUDNN_VERSION=7.6.0.64 
export UBUNTU_VERSION=18.04 
export TENSORFLOW_VERSION=1.15.0   

We recently also updated Docker on our server to 19.03. 
 
We have spent several weeks trying to solve this one problem and are kinda desperate at this point because we feel that for our cause, DIRT is the best option out there yet. Any help will be deeply appreciated.

_Originally posted by @au001 in https://github.com/pmh47/dirt/issues/54#issuecomment-596151757_

**Comment by pmh47** [comment] 2020-03-09 01:25
Please paste the output of `nvidia-smi -q` here, ideally run it both from inside and outside the docker container. Also tell me the base OS distro/version, linux kernel version, and nvidia driver version. Also add `std::cout << "eglQueryDeviceAttribEXT returns " << ` to the start of line 60 of `csrc/gl_common.h`, to have it print the return code of `eglQueryDeviceAttribEXT` (either add a suitable patch operation in the Dockerfile after the git checkout, or change it to check out a local version of the repo with that change made).

**Comment by au001** [comment] 2020-03-09 05:52
Thank you so much!
I have made the necessary outputs available in 3 different files in [this gist](https://gist.github.com/au001/ce58b2d864545c8bf92ada5362c0fd6e) in view of brevity of this thread. 

base OS distro/version: `CentOS Linux release 7.7.1908 (Core)`
linux kernel version: `Linux 3.10.0-957.21.2.el7.x86_64`
nvidia driver version: `418.67`

return code of `eglQueryDeviceAttribEXT`: will let you know shortly

**Comment by au001** [comment] 2020-03-09 09:37
return code of `eglQueryDeviceAttribEXT`: 0

I removed the previous docker image and built it again for these changes to `csrc/gl_common.h` to take effect (I used `LOG(INFO)` instead of `std::cout`):

```
        // Find which egl device matches the active cuda device, or use device zero for cpu mode (requiredCudaDevice == -1)
        int eglDeviceIndex = 0;
        LOG(INFO) << "before entering requiredCudaDevice: " << requiredCudaDevice; 
        if (requiredCudaDevice != -1) {
            for (; eglDeviceIndex < numDevices; ++eglDeviceIndex) {
                EGLAttrib cudaDeviceId = -1;
                LOG(INFO) << "eglQueryDeviceAttribEXT returns " << eglQueryDeviceAttribEXT(eglDevs[eglDeviceIndex], EGL_CUDA_DEVICE_NV, &cudaDeviceId);
                if (cudaDeviceId == requiredCudaDevice)
                    break;
            }
            if (eglDeviceIndex == numDevices)
                LOG(FATAL) << "none of " << numDevices << " egl devices matches the active cuda device";
            LOG(INFO) << "selected egl device #" << eglDeviceIndex << " to match cuda device #" << requiredCudaDevice << " for thread 0x" << std::hex << std::this_thread::get_id();
        }
```

Resulting output:

```
I have no name!@8b8486d4f874:~/anu-debug/dirt$ python tests/square_test.py
WARNING:tensorflow:From tests/square_test.py:41: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-03-09 09:23:12.524006: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-03-09 09:23:15.519862: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: Tesla V100-PCIE-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:21:00.0
2020-03-09 09:23:15.520326: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-03-09 09:23:15.521970: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-03-09 09:23:15.537057: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-03-09 09:23:15.537424: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-03-09 09:23:15.539373: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-03-09 09:23:15.541086: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-03-09 09:23:15.544829: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-09 09:23:15.548962: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-03-09 09:23:15.550558: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-09 09:23:15.563714: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1995940000 Hz
2020-03-09 09:23:15.566848: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x562c837c6cb0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-09 09:23:15.566908: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-03-09 09:23:15.696897: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x562c84031730 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-03-09 09:23:15.696960: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla V100-PCIE-32GB, Compute Capability 7.0
2020-03-09 09:23:15.699467: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: Tesla V100-PCIE-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:21:00.0
2020-03-09 09:23:15.699543: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-03-09 09:23:15.699574: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-03-09 09:23:15.699624: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-03-09 09:23:15.699654: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-03-09 09:23:15.699720: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-03-09 09:23:15.699757: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-03-09 09:23:15.699794: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-09 09:23:15.704337: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-03-09 09:23:15.704403: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-03-09 09:23:15.707083: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-09 09:23:15.707116: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2020-03-09 09:23:15.707137: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2020-03-09 09:23:15.711807: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30555 MB memory) -> physical GPU (device: 0, name: Tesla V100-PCIE-32GB, pci bus id: 0000:21:00.0, compute capability: 7.0)
2020-03-09 09:23:16.899682: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-03-09 09:23:16.905453: I /tmp/pip-req-build-baks3awx/csrc/gl_common.h:59] before entering requiredCudaDevice: 0
2020-03-09 09:23:16.905568: I /tmp/pip-req-build-baks3awx/csrc/gl_common.h:65] eglQueryDeviceAttribEXT returns 0
2020-03-09 09:23:16.905608: F /tmp/pip-req-build-baks3awx/csrc/gl_common.h:70] none of 1 egl devices matches the active cuda device
Aborted (core dumped)
```

**Comment by au001** [comment] 2020-03-09 10:01
Furthermore, I believe our script for running the docker image may shed more light on this. Contents of `start_dirtdocker.sh`:

```
#!/bin/sh
# usage: ./start_dirtdocker.sh <GPU number>
docker run -u $(id -u):$(id -g) --rm --runtime=nvidia -it -v /data:/data -e CUDA_VISIBLE_DEVICES=$1 -e USER=$USER -e HOME=/data/$USER -w $PWD dirtdocker/latest bash 
```

**Comment by pmh47** [comment] 2020-03-09 21:26
All your outputs look correct, and I have not been able to reproduce this, even using a very similar setup (CentOS 7, very slightly newer kernel and driver (`3.10.0-1062.12.1.el7.x86_64` and `418.126.02`), docker 19.03, 4x Tesla V100, same cuda/cudnn/tf versions as you -- but the default ubuntu 16.04 from the gist dockerfile). I assume the problem is that docker somehow changes the way GPUs are 'named' by EGL and CUDA, but I do not know why this is happening.

If you are using docker 19.03, try (as I did) using the built-in nvidia gpu support rather than nvidia-docker runtime -- remove `nvidia-docker2` package, and see the [new recommended method](https://github.com/NVIDIA/nvidia-docker#centos-7-docker-ce-rhel-7475-docker-ce-amazon-linux-12). Then use `--gpus '"device=0"'` [argument](https://github.com/NVIDIA/nvidia-docker#usage) to `docker run` to select/enable GPUs.

If it still doesn't work, paste the output of `export | grep NV` inside the container. Also check what error is returned by `eglQueryDeviceAttribEXT` -- add a line after that call in `gl_common.h` saying `LOG(INFO) << "eglGetError returns " << eglGetError();`.

Is it possible to test DIRT in a conda environment directly 'on the metal' (i.e. not in a docker container), to avoid possible issues introduced by docker?

**Comment by au001** [comment] 2020-03-11 19:34
Thanks! We are yet to try out your suggestions but here are some of the outputs even before that: 

Using ubuntu 16.04 gets us stuck at the first FATAL message in `gl_common.h`: `extensions eglQueryDevicesEXT, eglQueryDeviceAttribEXT and eglGetPlatformDisplayEXT not available`.

output of `export | grep NV` from inside the container:
```
declare -x NVIDIA_DRIVER_CAPABILITIES="compute,utility,graphics,compat32,utility"
declare -x NVIDIA_REQUIRE_CUDA="cuda>=10.0 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=410,driver<411"
declare -x NVIDIA_VISIBLE_DEVICES="all"
```
output of `eglGetError()`: `12292`

I'll provide updates shortly.

**Comment by pmh47** [comment] 2020-03-12 13:22
That error is `EGL_BAD_ATTRIBUTE`, which is surprising as it implies an EGL library is being used that doesn't 'understand' the `EGL_CUDA_DEVICE_NV` attribute -- which implies a non-nvidia EGL, or maybe a system GLVND that it thinks it's a non-nvidia device. In fact this matches with the error you had under 16.04 -- which is what you get if the wrong libEGL is in use (i.e. a mesa version, or another non-nvidia version that doesn't integrate with GLVND). This seems to imply that the base container `nvidia/cudagl` or the nvidia docker runtime is not set up right, and use of 18.04 hides this (as it has EGL implemented differently to 16.04).

Could you check if the correct EGL libraries are being used -- in the container, `ldd ~/dirt/dirt/librasterise.so` and `ls -l /usr/lib*/*/*GL*`. Also please run the second of those outside the container, as I think the nvidia docker runtime pulls user-mode 'pieces' of the driver from the base system.

Finally, please also print the value of `eglQueryDeviceStringEXT(eglDevs[eglDeviceIndex], EGL_EXTENSIONS)` at line 60 of `csrc/gl_common.h`.

**Comment by au001** [comment] 2020-03-14 05:18
Thanks again for your insights! I've tried using the built-in Nvidia GPU support but to no avail. 

The output of `export | grep NV` from inside the container is the same as the one outside from before except for the last line
```declare -x NVIDIA_VISIBLE_DEVICES="2"```
because of the `docker run` argument `--gpus '"device=2"'`

We're currently trying to install DIRT directly 'on the metal' and also on other servers like EC2 instances.

The output of `ldd ~/dirt/dirt/librasterise.so` both inside and outside the container is `No such file or directory` and the outputs of `ls -l /usr/lib*/*/*GL*` are here in [this gist](https://gist.github.com/au001/ee569abc21128389371cc10d1a8060e1).
And I am starting to see what you mention because there is no `nvidia.so` file name in any of the outputs as @WXinlong got in issue #13.   

It is further suggested by
```eglQueryDeviceStringEXT returns EGL_MESA_device_software```
Additionally, we also printed out
`active cuda device from rasterise_egl.cpp: 0`

From your suggestions on this issue page and others, we are trying to install/reinstall nvidia/cuda drivers. Could you also suggest what versions we may use?

**Comment by pmh47** [comment] 2020-03-14 09:27
Yes, looks like we're on the right track. Try a more wide 'find' command (e.g. anywhere in `/`) to locate any `*GL*` libraries on the base OS (outside container), as it didn't turn up anything at all there.

Regarding versions, any recent version of the driver (say 400 onwards), with cuda 10.0, and tensorflow 1.13.1 / 1.14 / 1.15 should work. Ubuntu (particularly 18.04) as the OS is much better-tested and more reliable than CentOS/etc. Various other tickets give caveats for specific version combinations that can go wrong due to binary incompatibilities / etc.

**Comment by au001** [comment] 2020-03-14 20:31
Thanks for your suggestions. Meanwhile, I added the accessible names with `find / -name *GL*` to the [previous gist](https://gist.github.com/au001/ee569abc21128389371cc10d1a8060e1).

**Comment by pmh47** [comment] 2020-03-15 14:03
It is surprising that there are no nvidia GL/EGL libraries on the base system. Did you install the nvidia driver using CentOS packages, or the nvidia runfile installer? If the former, which nvidia-related packages are installed?

**Comment by au001** [comment] 2020-04-08 11:15
Please excuse the delay in my response due to the current world events. 
It felt like a great success when we finally got the message "all pixels agree" after we ran square_test.py some days ago! Seemingly, the only changes we made were updating the nvidia driver to `440.64` and installing `CUDA 10.2` on the metal.

1) Base OS distro/version remained the same as before, `CentOS Linux release 7.7.1908 (Core)`
2) But Linux kernel version changed to your version: `Linux 3.10.0-1062.12.1.el7.x86_64`
3) `eglQueryDeviceAttribEXT` returned `1` this time
4) And, yes, we used docker 19.03's built-in nvidia GPU support with `--gpus '"device=0"'`
5) output of `eglGetError()`: `12288` which I guess means `EGL_SUCCESS` here
6) output of `ldd ~/dirt/dirt/librasterise.so` has always been `No such file or directory` and so when I did a system wide search with `find / -name *librasterise.so*` from within the container, I found it here: `/usr/local/lib/python3.7/dist-packages/dirt/librasterise.so`
7) And this time `eglQueryDeviceStringEXT returns EGL_NV_device_cuda EGL_EXT_device_drm`

Please find all the other outputs in [this success gist](https://gist.github.com/au001/b800db7e94e418d015b41eb74309fb87).

This might be outside the scope of DIRT but since our project relies heavily on Docker and we are trying to potentially enhance it by incorporating DIRT into our CNN/GAN, could you suggest how to merge DIRT Dockerfile with our project's current Dockerfile? Essentially, we are not able to use two `from` statements i.e., build from two base images from within the same Dockerfile. 

Thank you very much for your help all this while and the very best wishes in these uncertain times!

**Comment by pmh47** [comment] 2020-04-08 15:49
Great, glad you got it working!

For docker, note that modern versions do support 'multi-stage builds' that have multiple `FROM` commands. However, I think you will need the final container that you run the whole project in to use a `nvidia/cudagl` image as its base, to ensure the GL libraries exist at run time. Assuming you have some stack of images that ultimately derive from `nvidia/cuda`, then changing that to `nvidia/cudagl` with the same CUDA & OS versions should allow DIRT to work (assuming those versions are something DIRT supports). If your existing project cannot be built also in such a container, then how to fix it depends what conflicts arise.

I'll close this issue as the specific problem is resolved.

**Closed by pmh47** 2020-04-08 15:49 UTC
